### PR TITLE
It is useful when a callback is needed when image loads

### PR DESCRIPTION
**Pull request by alexhoo**
It is useful when a callback is needed when image loads

### CODE REVIEW

**Comment by orafaelfragoso** [comment]
@alexhoo Would you be so kind to fix the lint errors and squash your commits?

**Comment by alexhoo** [comment]
Sure, no problem ;)

**Comment by alexhoo** [comment]
Squashed the commits but have this linter errors:  
` error  Assignment to property of function parameter 'scope'  no-param-reassign`
This is not fixable in an angular application since angular injects dependencies as function parameters. Any ideas?

**Comment by orafaelfragoso** [comment]
@alexhoo You can tell the linter to ignore this line specifically. It should be fine.

**Comment by alexhoo** [comment]
hey man, sorry ...  lot of work. You're ready to go with it

**Pull request merged**
